// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Category struct {
	ID        int64
	Name      string
	User      int64
	CreatedAt time.Time
}

type Todo struct {
	ID        int64
	Title     string
	Content   string
	Done      bool
	CreatedBy int64
	Category  int64
	CreatedAt time.Time
}

type TodoPermission struct {
	UserID int64
	TodoID int64
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt time.Time
}
